name: Build and Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: build Sender
      run: g++ -Wall -Wextra -Werror --coverage -o SenderExe Sender/*.cpp
      
    - name: build Receiver
      run: g++ -Wall -Wextra -Werror --coverage -o ReceiverExe Receiver/Receiver.cpp
      
    - name: run Sender
      run: ./SenderExe
    
    - name: build SenderTest
      run: g++ -Wall -Wextra -Werror --coverage -o SenderTestExe SenderTest/SenderTest.cpp Sender/Sender.cpp
    
    - name: run SenderTest
      run: ./SenderTestExe
    
    - name: coverage report Sender
      run: gcov -r Sender.cpp
      
    - name: coverage report Receiver
      run: gcov -r Receiver.cpp
